baseURL = "https://blog.5ebec.dev/"
defaultContentLanguage = "ja"
languageCode = "ja"
title = "#a5ebec"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["a5ebec", "orange", "blue", "red", "green", "pink"]
  themeColor = "a5ebec"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  favicon = "img/favicon/favicon.ico"

  subtitle = "5ebec's scribbled blog"
  author = "5ebec"
  keywords = "blog"
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"

[params.logo]
  logoText = "#a5ebec"
  logoHomeLink = "/"

[social]
  twitter = "5ebec"

[taxonomies]
  tag = "tags"

[menu]
[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3
