backend:
  name: github
  repo: 5ebec/pothooks

publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "Posts"
    identifier_field: title
    folder: "content/posts"
    create: true
    slug: "{{fields.slug}}"
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Featured Image"
        name: "cover"
        widget: "image"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["julia", "paper"]
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Markup"
        name: "markup"
        widget: "hidden"
        default: "mmark"
      - label: "Body"
        name: "body"
        widget: "markdown"
