name: scheduler

on:
  schedule:
    - cron: '35 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Post netlify build hooks
      run: curl -X POST -d {} ${{ secrets.BUILD_HOOKS_URL }}
